[package]
name = "folio"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
pretty_env_logger = "0.5"
figment = { version = "0.10", features = ["env", "toml"] }
rocket = { version = "0.5.1", features = ["json"] }
rand = "0.8"

[dev-dependencies]
tempfile = "3.8"
